version: '3.5'
services:
    db:
        image: mongo
        container_name: MongoDB
        environment:
            - PUID=1000
            - PGID=1000
            - MONGO_INITDB_ROOT_USERNAME=vigilante
            - MONGO_INITDB_ROOT_PASSWORD=sirikuu
        volumes:
            - mongodb-data:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=db
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_ADMINUSERNAME=vigilante
            - ME_CONFIG_MONGODB_ADMINPASSWORD=sirikuu
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=admin1234
        volumes:
            - mongodb-data
        depends_on:
            - db
        ports:
            - 8081:8081
        restart: on-failure
volumes:
    mongodb-data: